### ISSUE TITLE
Not able to download data anymore

### ISSUE THREAD

**Issue by anderzzz** [visipedia/fgvcx_fungi_comp#2]
Is the training data still available? I know the Kaggle competition is over, but I am interested to explore the fungi classification task. However, when I follow the link to the training dataset (or any other of datasets), the deic.dk site does not return anything and eventually times out. With Safari the message reads: 

> Safari can’t open the page “https://data.deic.dk/shared/2fd47962a38e2a70570f3be027cea57f” because the server where this page is located isn’t responding.

**Comment by MattBlissett** [comment]
Hi @anderzzz,

I've copied the data to https://labs.gbif.org/fgvcx/2018/ (except `test_information.tgz`, which I don't have).

**Comment by anderzzz** [comment]
As far as I am concerned, this issue has been resolved. Thanks.
